{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-base.fullname" . }}
  labels:
    {{- include "chart-base.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secret.variables | nindent 2 }}
{{- end }}
