{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-base.fullname" . }}
  labels:
    {{- include "chart-base.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.headless }}
  clusterIP: None
  {{- end }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol | default "TCP" }}
      targetPort: {{ .targetPort }}
      {{- if and (eq $.Values.service.type "NodePort") (hasKey . "nodePort") }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "chart-base.selectorLabels" . | nindent 4 }}
{{- end }}
