{{- if and .Values.psk.enabled .Values.psk.value (not .Values.psk.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zabbix-proxy.pskSecretName" . }}
  labels:
    {{- include "zabbix-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  proxy.psk: {{ .Values.psk.value | quote }}
{{- end }}
