apiVersion: v1
kind: Service
metadata:
  name: {{ include "zabbix-proxy.fullname" . }}
  labels:
    {{- include "zabbix-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.headless }}
  clusterIP: None
  {{- end }}
  ports:
    - name: zbx-proxy
      port: {{ .Values.service.port }}
      targetPort: zbx-proxy
      protocol: TCP
  selector:
    {{- include "zabbix-proxy.selectorLabels" . | nindent 4 }}
