apiVersion: v2
name: zabbix-proxy
description: Chart Helm de plumbing k8s para Zabbix Proxy (SQLite). StatefulSet + Service + PVC opcional. Toda config do proxy via extraEnv.
type: application
version: 0.1.0
appVersion: "7.0.16"
keywords:
  - zabbix
  - zabbix-proxy
  - monitoring
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: Robert Silva
    email: robertsilva.info@gmail.com
home: https://github.com/robertsilvatech/rst-helm-charts
sources:
  - https://github.com/robertsilvatech/rst-helm-charts
  - https://www.zabbix.com/documentation/current/en/manual/distributed_monitoring/proxies
annotations:
  category: Monitoring
